"""
# ======================================================================================
# STEPS / WORKFLOW
# ======================================================================================
# 1. Offline — Execute once and save
#    - Generate a search_text → embedding vector for each of the 13,939 ESCO records.
#    - Save the results to a .npy file (data/processed/esco_embeddings.npy).
#    - Save the label list (to know which vector belongs to which label).
#
# 2. Online — For every query
#    - Convert the extracted skill (e.g., "Python scientific stack") into an embedding.
#    - Calculate cosine similarity against the 13,939 saved vectors.
#    - Return the top 5 highest-scoring results.
#
#
# Model Selection: 
#    - all-MiniLM-L6-v2 — Lightweight, fast, and sufficient for English. 
#    - Ideal for the initial implementation.

# FILE STRUCTURE:
    data/processed/esco_skill_dictionary.json  ← currently exists, contains ESCO data

    data/processed/esco_embeddings.npy         ← will be generated by this script, contains 13,939 x 384 float32 vectors
    -line 0  →  [0.23, -0.11, 0.87, ...]
    -line 1  →  [0.41,  0.07, 0.34, ...]
    -line 2  →  [0.12,  0.55, 0.21, ...]

    data/processed/esco_labels.json            ← will be generated by this script
    line 0  =  "Python (computer programming)"
    line 1  =  "use Python libraries"
    line 2  =  "manage musical staff"
=============================================================
"""

import json
import numpy as np
from pathlib import Path
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

# --- Paths ---
DATA_DIR = Path("data/processed")
ESCO_JSON = DATA_DIR / "esco_skill_dictionary.json"
EMBEDDINGS_PATH = DATA_DIR / "esco_embeddings.npy"
LABELS_PATH = DATA_DIR / "esco_labels.json"

MODEL_NAME = "all-MiniLM-L6-v2"


# =============================================================
# STEP 1: OFFLINE — Embedding create and save
# =============================================================

def build_and_save_embeddings():
    """
    ESCO JSON -> search_text-> embedding -> save as .npy 
    one time execution, can be commented out after the first run.
    """
    print("ESCO data uploaded...")
    with open(ESCO_JSON, "r", encoding="utf-8") as f:
        esco_data = json.load(f)

    labels = []
    texts = []

    for label, info in esco_data.items():
        alt_names = info.get("alternative_names", [])
        description = info.get("description", "")
        search_text = " ".join([label] + alt_names + [description])
        labels.append(label)
        texts.append(search_text)

    print(f"{len(texts)} records prepared. Loading model: {MODEL_NAME}")
    model = SentenceTransformer(MODEL_NAME)

    print("Generating embeddings... (this may take a while)")
    embeddings = model.encode(texts, show_progress_bar=True, batch_size=64)

    np.save(EMBEDDINGS_PATH, embeddings)
    with open(LABELS_PATH, "w", encoding="utf-8") as f:
        json.dump(labels, f, ensure_ascii=False)

    print(f"Kaydedildi:")
    print(f"  {EMBEDDINGS_PATH}  ({embeddings.shape})")
    print(f"  {LABELS_PATH}  ({len(labels)} label)")


# =============================================================
# STEP 2: ONLINE — semantic search for every query
# =============================================================

def load_index():
    """saved embedding and labels upload"""
    embeddings = np.load(EMBEDDINGS_PATH)
    with open(LABELS_PATH, "r", encoding="utf-8") as f:
        labels = json.load(f)
    return embeddings, labels


def semantic_search(query, embeddings, labels, model, top_k=5):
    """
    turn the query into an embedding, 
    calculate cosine similarity against the index, 
    and return top_k results.
    """
    query_vec = model.encode([query])
    scores = cosine_similarity(query_vec, embeddings)[0]
    top_indices = np.argsort(scores)[::-1][:top_k]

    results = []
    for idx in top_indices:
        results.append((scores[idx], labels[idx]))
    return results


# =============================================================
# MAIN
# =============================================================

if __name__ == "__main__":
    if not EMBEDDINGS_PATH.exists():
        build_and_save_embeddings()
    else:
        print("Embedding file found, loading...")

    embeddings, labels = load_index()
    model = SentenceTransformer(MODEL_NAME)


    test_queries = [
    "Production-grade Machine Learning Models",
    "Natural Language Processing Systems",
    "Computer Vision Systems",
    "Foundation Model Fine-Tuning",
    "Scalable Machine Learning Pipelines",
    "Machine Learning Performance Optimization",
    "Machine Learning Model Deployment Automation",
    "Model Drift Monitoring",
    "Distributed Training Systems",
    "End-to-End Machine Learning Delivery",
    "High-Throughput Inference Systems",
    "Exploratory Data Analysis",
    "Feature Engineering",
    "Model Training",
    "Model Evaluation",
    "Gradient Debugging",
    "Academic Paper Implementation",
    "Cross-Functional Collaboration",
    "Engineering Quality Mindset",
    "Machine Learning Theory",
    "Statistical Modeling Techniques",
    "Python Programming",
    "Data Structures and Algorithms",
    "Distributed System Design",
    "Modern Machine Learning Stack",
    "Transformer Architectures",
    ]

    for query in test_queries:
        print(f"\nQuery: {query}")
        results = semantic_search(query, embeddings, labels, model, top_k=5)
        for score, label in results:
            print(f"  score={score:.4f} | {label}")